-- +goose Up

-- Full relational schema for the Jade & João wedding API.
-- IDs are UUIDs generated by the database; money is integer centavos (BRL);
-- timestamps are timestamptz stored in UTC.

create table guest_groups (
    id         uuid primary key default gen_random_uuid(),
    label      text not null,
    created_at timestamptz not null default now()
);

create table guests (
    id              uuid primary key default gen_random_uuid(),
    group_id        uuid not null references guest_groups (id) on delete cascade,
    full_name       text not null,
    -- trim + casefold + strip diacritics + collapse inner whitespace, computed in Go.
    -- Globally unique: homonyms are import conflicts, resolved manually by qualifier.
    normalized_name text not null unique,
    is_primary      boolean not null default false,
    category        text check (category in ('adult', 'child', 'baby', 'elderly')),
    attending       text not null default 'pending' check (attending in ('pending', 'yes', 'no')),
    responded_at    timestamptz,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

create index guests_group_id_idx on guests (group_id);

create table gifts (
    id             uuid primary key default gen_random_uuid(),
    title          text not null,
    description    text not null default '',
    image_url      text,
    goal_centavos  bigint check (goal_centavos > 0),
    quota_centavos bigint check (quota_centavos > 0),
    max_units      integer check (max_units > 0),
    active         boolean not null default true,
    sort           integer not null default 0,
    created_at     timestamptz not null default now()
);

create index gifts_active_sort_idx on gifts (active, sort);

-- Append-only ledger: rows are never deleted; only status transitions
-- (declared -> confirmed | cancelled) performed by the admin.
create table contributions (
    id               uuid primary key default gen_random_uuid(),
    gift_id          uuid not null references gifts (id),
    group_id         uuid references guest_groups (id) on delete set null,
    contributor_name text not null,
    amount_centavos  bigint not null check (amount_centavos > 0),
    status           text not null default 'declared' check (status in ('declared', 'confirmed', 'cancelled')),
    created_at       timestamptz not null default now(),
    confirmed_at     timestamptz
);

create index contributions_gift_id_status_idx on contributions (gift_id, status);

create table messages (
    id          uuid primary key default gen_random_uuid(),
    group_id    uuid references guest_groups (id) on delete set null,
    author_name text not null,
    body        text not null,
    status      text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
    created_at  timestamptz not null default now()
);

create index messages_status_idx on messages (status);

-- Editorial content: one typed JSONB payload per section slug. The slug set is
-- closed (seeded by migration 00002); the admin surface is update-only.
create table sections (
    slug       text primary key,
    payload    jsonb not null,
    enabled    boolean not null default true,
    updated_at timestamptz not null default now()
);

create table media (
    id          uuid primary key default gen_random_uuid(),
    bucket_path text not null unique,
    public_url  text not null,
    alt         text,
    created_at  timestamptz not null default now()
);

create table imports (
    id         uuid primary key default gen_random_uuid(),
    started_at timestamptz not null default now(),
    report     jsonb not null
);

-- Defense-in-depth: RLS enabled with ZERO policies on every table. The Supabase
-- Data API (PostgREST) is also closed in the dashboard, but even if it were
-- exposed, anon/authenticated roles would see nothing. The API itself connects
-- as the table owner (postgres), which bypasses RLS unless FORCE is set — so
-- these statements do not affect the API. Never add policies here.
alter table guest_groups  enable row level security;
alter table guests        enable row level security;
alter table gifts         enable row level security;
alter table contributions enable row level security;
alter table messages      enable row level security;
alter table sections      enable row level security;
alter table media         enable row level security;
alter table imports       enable row level security;

-- +goose Down

drop table imports;
drop table media;
drop table sections;
drop table messages;
drop table contributions;
drop table gifts;
drop table guests;
drop table guest_groups;
