// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: gifts.sql

package giftsdb

import (
	"context"

	"github.com/google/uuid"
)

const getGiftForUpdate = `-- name: GetGiftForUpdate :one
select id, quota_centavos, max_units, active
from gifts
where id = $1
for update
`

type GetGiftForUpdateRow struct {
	ID            uuid.UUID
	QuotaCentavos *int64
	MaxUnits      *int32
	Active        bool
}

func (q *Queries) GetGiftForUpdate(ctx context.Context, id uuid.UUID) (GetGiftForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getGiftForUpdate, id)
	var i GetGiftForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.QuotaCentavos,
		&i.MaxUnits,
		&i.Active,
	)
	return i, err
}

const getGiftWithProgress = `-- name: GetGiftWithProgress :one
select g.id, g.title, g.description, g.image_url, g.goal_centavos, g.quota_centavos,
       g.max_units, g.active, g.sort,
       coalesce(sum(c.amount_centavos) filter (where c.status = 'declared'), 0)::bigint  as declared_centavos,
       coalesce(sum(c.amount_centavos) filter (where c.status = 'confirmed'), 0)::bigint as confirmed_centavos
from gifts g
left join contributions c on c.gift_id = g.id
where g.id = $1
group by g.id
`

type GetGiftWithProgressRow struct {
	ID                uuid.UUID
	Title             string
	Description       string
	ImageUrl          *string
	GoalCentavos      *int64
	QuotaCentavos     *int64
	MaxUnits          *int32
	Active            bool
	Sort              int32
	DeclaredCentavos  int64
	ConfirmedCentavos int64
}

func (q *Queries) GetGiftWithProgress(ctx context.Context, id uuid.UUID) (GetGiftWithProgressRow, error) {
	row := q.db.QueryRow(ctx, getGiftWithProgress, id)
	var i GetGiftWithProgressRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ImageUrl,
		&i.GoalCentavos,
		&i.QuotaCentavos,
		&i.MaxUnits,
		&i.Active,
		&i.Sort,
		&i.DeclaredCentavos,
		&i.ConfirmedCentavos,
	)
	return i, err
}

const insertContribution = `-- name: InsertContribution :one
insert into contributions (gift_id, group_id, contributor_name, amount_centavos)
values ($1, $2, $3, $4)
returning id, gift_id, group_id, contributor_name, amount_centavos, status, created_at, confirmed_at
`

type InsertContributionParams struct {
	GiftID          uuid.UUID
	GroupID         uuid.NullUUID
	ContributorName string
	AmountCentavos  int64
}

func (q *Queries) InsertContribution(ctx context.Context, arg InsertContributionParams) (Contribution, error) {
	row := q.db.QueryRow(ctx, insertContribution,
		arg.GiftID,
		arg.GroupID,
		arg.ContributorName,
		arg.AmountCentavos,
	)
	var i Contribution
	err := row.Scan(
		&i.ID,
		&i.GiftID,
		&i.GroupID,
		&i.ContributorName,
		&i.AmountCentavos,
		&i.Status,
		&i.CreatedAt,
		&i.ConfirmedAt,
	)
	return i, err
}

const listGiftsWithProgress = `-- name: ListGiftsWithProgress :many
select g.id, g.title, g.description, g.image_url, g.goal_centavos, g.quota_centavos,
       g.max_units, g.active, g.sort,
       coalesce(sum(c.amount_centavos) filter (where c.status = 'declared'), 0)::bigint  as declared_centavos,
       coalesce(sum(c.amount_centavos) filter (where c.status = 'confirmed'), 0)::bigint as confirmed_centavos
from gifts g
left join contributions c on c.gift_id = g.id
where g.active or not $1::boolean
group by g.id
order by g.sort, g.created_at
`

type ListGiftsWithProgressRow struct {
	ID                uuid.UUID
	Title             string
	Description       string
	ImageUrl          *string
	GoalCentavos      *int64
	QuotaCentavos     *int64
	MaxUnits          *int32
	Active            bool
	Sort              int32
	DeclaredCentavos  int64
	ConfirmedCentavos int64
}

func (q *Queries) ListGiftsWithProgress(ctx context.Context, onlyActive bool) ([]ListGiftsWithProgressRow, error) {
	rows, err := q.db.Query(ctx, listGiftsWithProgress, onlyActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGiftsWithProgressRow
	for rows.Next() {
		var i ListGiftsWithProgressRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.ImageUrl,
			&i.GoalCentavos,
			&i.QuotaCentavos,
			&i.MaxUnits,
			&i.Active,
			&i.Sort,
			&i.DeclaredCentavos,
			&i.ConfirmedCentavos,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumGiftNonCancelled = `-- name: SumGiftNonCancelled :one
select coalesce(sum(amount_centavos), 0)::bigint
from contributions
where gift_id = $1 and status <> 'cancelled'
`

func (q *Queries) SumGiftNonCancelled(ctx context.Context, giftID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, sumGiftNonCancelled, giftID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
