// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: gifts.sql

package giftsdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deactivateGift = `-- name: DeactivateGift :execrows
update gifts
set active = false
where id = $1
`

func (q *Queries) DeactivateGift(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deactivateGift, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteGiftIfNoContributions = `-- name: DeleteGiftIfNoContributions :execrows
delete from gifts
where gifts.id = $1
  and not exists (select 1 from contributions c where c.gift_id = gifts.id)
`

func (q *Queries) DeleteGiftIfNoContributions(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGiftIfNoContributions, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getContribution = `-- name: GetContribution :one
select id, gift_id, group_id, contributor_name, amount_centavos, status, created_at, confirmed_at
from contributions
where id = $1
`

func (q *Queries) GetContribution(ctx context.Context, id uuid.UUID) (Contribution, error) {
	row := q.db.QueryRow(ctx, getContribution, id)
	var i Contribution
	err := row.Scan(
		&i.ID,
		&i.GiftID,
		&i.GroupID,
		&i.ContributorName,
		&i.AmountCentavos,
		&i.Status,
		&i.CreatedAt,
		&i.ConfirmedAt,
	)
	return i, err
}

const getGiftForUpdate = `-- name: GetGiftForUpdate :one
select id, kind, quota_centavos, max_units, active
from gifts
where id = $1
for update
`

type GetGiftForUpdateRow struct {
	ID            uuid.UUID
	Kind          string
	QuotaCentavos *int64
	MaxUnits      *int32
	Active        bool
}

func (q *Queries) GetGiftForUpdate(ctx context.Context, id uuid.UUID) (GetGiftForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getGiftForUpdate, id)
	var i GetGiftForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.QuotaCentavos,
		&i.MaxUnits,
		&i.Active,
	)
	return i, err
}

const getGiftWithProgress = `-- name: GetGiftWithProgress :one
select g.id, g.title, g.description, g.image_url, g.kind, g.platform, g.external_url,
       g.goal_centavos, g.quota_centavos, g.max_units, g.active, g.sort,
       coalesce(sum(c.amount_centavos) filter (where c.status = 'declared'), 0)::bigint  as declared_centavos,
       coalesce(sum(c.amount_centavos) filter (where c.status = 'confirmed'), 0)::bigint as confirmed_centavos
from gifts g
left join contributions c on c.gift_id = g.id
where g.id = $1
group by g.id
`

type GetGiftWithProgressRow struct {
	ID                uuid.UUID
	Title             string
	Description       string
	ImageUrl          *string
	Kind              string
	Platform          *string
	ExternalUrl       *string
	GoalCentavos      *int64
	QuotaCentavos     *int64
	MaxUnits          *int32
	Active            bool
	Sort              int32
	DeclaredCentavos  int64
	ConfirmedCentavos int64
}

func (q *Queries) GetGiftWithProgress(ctx context.Context, id uuid.UUID) (GetGiftWithProgressRow, error) {
	row := q.db.QueryRow(ctx, getGiftWithProgress, id)
	var i GetGiftWithProgressRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ImageUrl,
		&i.Kind,
		&i.Platform,
		&i.ExternalUrl,
		&i.GoalCentavos,
		&i.QuotaCentavos,
		&i.MaxUnits,
		&i.Active,
		&i.Sort,
		&i.DeclaredCentavos,
		&i.ConfirmedCentavos,
	)
	return i, err
}

const insertContribution = `-- name: InsertContribution :one
insert into contributions (gift_id, group_id, contributor_name, amount_centavos)
values ($1, $2, $3, $4)
returning id, gift_id, group_id, contributor_name, amount_centavos, status, created_at, confirmed_at
`

type InsertContributionParams struct {
	GiftID          uuid.UUID
	GroupID         uuid.NullUUID
	ContributorName string
	AmountCentavos  int64
}

func (q *Queries) InsertContribution(ctx context.Context, arg InsertContributionParams) (Contribution, error) {
	row := q.db.QueryRow(ctx, insertContribution,
		arg.GiftID,
		arg.GroupID,
		arg.ContributorName,
		arg.AmountCentavos,
	)
	var i Contribution
	err := row.Scan(
		&i.ID,
		&i.GiftID,
		&i.GroupID,
		&i.ContributorName,
		&i.AmountCentavos,
		&i.Status,
		&i.CreatedAt,
		&i.ConfirmedAt,
	)
	return i, err
}

const insertGift = `-- name: InsertGift :one
insert into gifts (title, description, image_url, kind, platform, external_url,
                   goal_centavos, quota_centavos, max_units, active, sort)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
returning id
`

type InsertGiftParams struct {
	Title         string
	Description   string
	ImageUrl      *string
	Kind          string
	Platform      *string
	ExternalUrl   *string
	GoalCentavos  *int64
	QuotaCentavos *int64
	MaxUnits      *int32
	Active        bool
	Sort          int32
}

func (q *Queries) InsertGift(ctx context.Context, arg InsertGiftParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertGift,
		arg.Title,
		arg.Description,
		arg.ImageUrl,
		arg.Kind,
		arg.Platform,
		arg.ExternalUrl,
		arg.GoalCentavos,
		arg.QuotaCentavos,
		arg.MaxUnits,
		arg.Active,
		arg.Sort,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listContributions = `-- name: ListContributions :many
select c.id, c.gift_id, g.title as gift_title, c.group_id, c.contributor_name,
       c.amount_centavos, c.status, c.created_at, c.confirmed_at
from contributions c
join gifts g on g.id = c.gift_id
where ($1::text = '' or c.status = $1::text)
order by c.created_at desc
`

type ListContributionsRow struct {
	ID              uuid.UUID
	GiftID          uuid.UUID
	GiftTitle       string
	GroupID         uuid.NullUUID
	ContributorName string
	AmountCentavos  int64
	Status          string
	CreatedAt       time.Time
	ConfirmedAt     *time.Time
}

func (q *Queries) ListContributions(ctx context.Context, statusFilter string) ([]ListContributionsRow, error) {
	rows, err := q.db.Query(ctx, listContributions, statusFilter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContributionsRow
	for rows.Next() {
		var i ListContributionsRow
		if err := rows.Scan(
			&i.ID,
			&i.GiftID,
			&i.GiftTitle,
			&i.GroupID,
			&i.ContributorName,
			&i.AmountCentavos,
			&i.Status,
			&i.CreatedAt,
			&i.ConfirmedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGiftsWithProgress = `-- name: ListGiftsWithProgress :many
select g.id, g.title, g.description, g.image_url, g.kind, g.platform, g.external_url,
       g.goal_centavos, g.quota_centavos, g.max_units, g.active, g.sort,
       coalesce(sum(c.amount_centavos) filter (where c.status = 'declared'), 0)::bigint  as declared_centavos,
       coalesce(sum(c.amount_centavos) filter (where c.status = 'confirmed'), 0)::bigint as confirmed_centavos
from gifts g
left join contributions c on c.gift_id = g.id
where g.active or not $1::boolean
group by g.id
order by g.sort, g.created_at
`

type ListGiftsWithProgressRow struct {
	ID                uuid.UUID
	Title             string
	Description       string
	ImageUrl          *string
	Kind              string
	Platform          *string
	ExternalUrl       *string
	GoalCentavos      *int64
	QuotaCentavos     *int64
	MaxUnits          *int32
	Active            bool
	Sort              int32
	DeclaredCentavos  int64
	ConfirmedCentavos int64
}

func (q *Queries) ListGiftsWithProgress(ctx context.Context, onlyActive bool) ([]ListGiftsWithProgressRow, error) {
	rows, err := q.db.Query(ctx, listGiftsWithProgress, onlyActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGiftsWithProgressRow
	for rows.Next() {
		var i ListGiftsWithProgressRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.ImageUrl,
			&i.Kind,
			&i.Platform,
			&i.ExternalUrl,
			&i.GoalCentavos,
			&i.QuotaCentavos,
			&i.MaxUnits,
			&i.Active,
			&i.Sort,
			&i.DeclaredCentavos,
			&i.ConfirmedCentavos,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumGiftNonCancelled = `-- name: SumGiftNonCancelled :one
select coalesce(sum(amount_centavos), 0)::bigint
from contributions
where gift_id = $1 and status <> 'cancelled'
`

func (q *Queries) SumGiftNonCancelled(ctx context.Context, giftID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, sumGiftNonCancelled, giftID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateContributionStatus = `-- name: UpdateContributionStatus :one
update contributions
set status = $1::text,
    confirmed_at = case
        when $1::text = 'confirmed' then now()
        when $1::text = 'cancelled' then null
        else confirmed_at
    end
where id = $2
  and (
    ($1::text = 'confirmed' and status = 'declared')
    or ($1::text = 'cancelled' and status in ('declared', 'confirmed'))
  )
returning id, gift_id, group_id, contributor_name, amount_centavos, status, created_at, confirmed_at
`

type UpdateContributionStatusParams struct {
	Status string
	ID     uuid.UUID
}

// Legal transitions only: declared -> confirmed, declared|confirmed -> cancelled.
// Cancelling clears confirmed_at; zero rows means unknown id OR illegal move.
func (q *Queries) UpdateContributionStatus(ctx context.Context, arg UpdateContributionStatusParams) (Contribution, error) {
	row := q.db.QueryRow(ctx, updateContributionStatus, arg.Status, arg.ID)
	var i Contribution
	err := row.Scan(
		&i.ID,
		&i.GiftID,
		&i.GroupID,
		&i.ContributorName,
		&i.AmountCentavos,
		&i.Status,
		&i.CreatedAt,
		&i.ConfirmedAt,
	)
	return i, err
}

const updateGift = `-- name: UpdateGift :execrows
update gifts
set title = $2, description = $3, image_url = $4, kind = $5, platform = $6,
    external_url = $7, goal_centavos = $8, quota_centavos = $9, max_units = $10,
    active = $11, sort = $12
where gifts.id = $1
  and (gifts.kind = $5 or not exists (select 1 from contributions c where c.gift_id = gifts.id))
`

type UpdateGiftParams struct {
	ID            uuid.UUID
	Title         string
	Description   string
	ImageUrl      *string
	Kind          string
	Platform      *string
	ExternalUrl   *string
	GoalCentavos  *int64
	QuotaCentavos *int64
	MaxUnits      *int32
	Active        bool
	Sort          int32
}

// Kind flips are guarded IN the statement (no check-then-act race with a
// concurrent Declare): the update only applies when the kind is unchanged or
// the gift has no ledger rows. Zero rows = unknown id OR locked kind.
func (q *Queries) UpdateGift(ctx context.Context, arg UpdateGiftParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateGift,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.ImageUrl,
		arg.Kind,
		arg.Platform,
		arg.ExternalUrl,
		arg.GoalCentavos,
		arg.QuotaCentavos,
		arg.MaxUnits,
		arg.Active,
		arg.Sort,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
