// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: importer.sql

package importerdb

import (
	"context"

	"github.com/google/uuid"
)

const insertGuestGroup = `-- name: InsertGuestGroup :one
insert into guest_groups (label)
values ($1)
returning id
`

func (q *Queries) InsertGuestGroup(ctx context.Context, label string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertGuestGroup, label)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertImportReport = `-- name: InsertImportReport :one
insert into imports (report)
values ($1)
returning id
`

func (q *Queries) InsertImportReport(ctx context.Context, report []byte) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertImportReport, report)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertImportedGuest = `-- name: InsertImportedGuest :one
insert into guests (group_id, full_name, normalized_name, is_primary, category)
values ($1, $2, $3, $4, $5)
returning id
`

type InsertImportedGuestParams struct {
	GroupID        uuid.UUID
	FullName       string
	NormalizedName string
	IsPrimary      bool
	Category       *string
}

func (q *Queries) InsertImportedGuest(ctx context.Context, arg InsertImportedGuestParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertImportedGuest,
		arg.GroupID,
		arg.FullName,
		arg.NormalizedName,
		arg.IsPrimary,
		arg.Category,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listGroupsForImport = `-- name: ListGroupsForImport :many
select id, label
from guest_groups
`

type ListGroupsForImportRow struct {
	ID    uuid.UUID
	Label string
}

func (q *Queries) ListGroupsForImport(ctx context.Context) ([]ListGroupsForImportRow, error) {
	rows, err := q.db.Query(ctx, listGroupsForImport)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupsForImportRow
	for rows.Next() {
		var i ListGroupsForImportRow
		if err := rows.Scan(&i.ID, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGuestsForImport = `-- name: ListGuestsForImport :many
select id, group_id, full_name, normalized_name, is_primary, category
from guests
`

type ListGuestsForImportRow struct {
	ID             uuid.UUID
	GroupID        uuid.UUID
	FullName       string
	NormalizedName string
	IsPrimary      bool
	Category       *string
}

func (q *Queries) ListGuestsForImport(ctx context.Context) ([]ListGuestsForImportRow, error) {
	rows, err := q.db.Query(ctx, listGuestsForImport)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGuestsForImportRow
	for rows.Next() {
		var i ListGuestsForImportRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.FullName,
			&i.NormalizedName,
			&i.IsPrimary,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setGroupPrimary = `-- name: SetGroupPrimary :exec
update guests
set is_primary = (id = $1::uuid), updated_at = now()
where group_id = $2::uuid
`

type SetGroupPrimaryParams struct {
	GuestID uuid.UUID
	GroupID uuid.UUID
}

func (q *Queries) SetGroupPrimary(ctx context.Context, arg SetGroupPrimaryParams) error {
	_, err := q.db.Exec(ctx, setGroupPrimary, arg.GuestID, arg.GroupID)
	return err
}

const updateGroupLabel = `-- name: UpdateGroupLabel :exec
update guest_groups
set label = $2
where id = $1
`

type UpdateGroupLabelParams struct {
	ID    uuid.UUID
	Label string
}

func (q *Queries) UpdateGroupLabel(ctx context.Context, arg UpdateGroupLabelParams) error {
	_, err := q.db.Exec(ctx, updateGroupLabel, arg.ID, arg.Label)
	return err
}

const updateGuestIdentity = `-- name: UpdateGuestIdentity :exec
update guests
set full_name = $2, category = $3, updated_at = now()
where id = $1
`

type UpdateGuestIdentityParams struct {
	ID       uuid.UUID
	FullName string
	Category *string
}

func (q *Queries) UpdateGuestIdentity(ctx context.Context, arg UpdateGuestIdentityParams) error {
	_, err := q.db.Exec(ctx, updateGuestIdentity, arg.ID, arg.FullName, arg.Category)
	return err
}
