// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package importerdb

import (
	"time"

	"github.com/google/uuid"
)

type Contribution struct {
	ID              uuid.UUID
	GiftID          uuid.UUID
	GroupID         uuid.NullUUID
	ContributorName string
	AmountCentavos  int64
	Status          string
	CreatedAt       time.Time
	ConfirmedAt     *time.Time
}

type Gift struct {
	ID            uuid.UUID
	Title         string
	Description   string
	ImageUrl      *string
	GoalCentavos  *int64
	QuotaCentavos *int64
	MaxUnits      *int32
	Active        bool
	Sort          int32
	CreatedAt     time.Time
}

type Guest struct {
	ID             uuid.UUID
	GroupID        uuid.UUID
	FullName       string
	NormalizedName string
	IsPrimary      bool
	Category       *string
	Attending      string
	RespondedAt    *time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type GuestGroup struct {
	ID        uuid.UUID
	Label     string
	CreatedAt time.Time
}

type Import struct {
	ID        uuid.UUID
	StartedAt time.Time
	Report    []byte
}

type Medium struct {
	ID         uuid.UUID
	BucketPath string
	PublicUrl  string
	Alt        *string
	CreatedAt  time.Time
}

type Message struct {
	ID         uuid.UUID
	GroupID    uuid.NullUUID
	AuthorName string
	Body       string
	Status     string
	CreatedAt  time.Time
}

type Section struct {
	Slug      string
	Payload   []byte
	Enabled   bool
	UpdatedAt time.Time
}
