// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: guests.sql

package guestsdb

import (
	"context"

	"github.com/google/uuid"
)

const getGuestByNormalizedName = `-- name: GetGuestByNormalizedName :one
select id, group_id, full_name, is_primary, category, attending
from guests
where normalized_name = $1
`

type GetGuestByNormalizedNameRow struct {
	ID        uuid.UUID
	GroupID   uuid.UUID
	FullName  string
	IsPrimary bool
	Category  *string
	Attending string
}

func (q *Queries) GetGuestByNormalizedName(ctx context.Context, normalizedName string) (GetGuestByNormalizedNameRow, error) {
	row := q.db.QueryRow(ctx, getGuestByNormalizedName, normalizedName)
	var i GetGuestByNormalizedNameRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.FullName,
		&i.IsPrimary,
		&i.Category,
		&i.Attending,
	)
	return i, err
}

const getGuestGroup = `-- name: GetGuestGroup :one
select id, label
from guest_groups
where id = $1
`

type GetGuestGroupRow struct {
	ID    uuid.UUID
	Label string
}

func (q *Queries) GetGuestGroup(ctx context.Context, id uuid.UUID) (GetGuestGroupRow, error) {
	row := q.db.QueryRow(ctx, getGuestGroup, id)
	var i GetGuestGroupRow
	err := row.Scan(&i.ID, &i.Label)
	return i, err
}

const listAllGroups = `-- name: ListAllGroups :many
select id, label
from guest_groups
order by label, id
`

type ListAllGroupsRow struct {
	ID    uuid.UUID
	Label string
}

func (q *Queries) ListAllGroups(ctx context.Context) ([]ListAllGroupsRow, error) {
	rows, err := q.db.Query(ctx, listAllGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllGroupsRow
	for rows.Next() {
		var i ListAllGroupsRow
		if err := rows.Scan(&i.ID, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllGuests = `-- name: ListAllGuests :many
select id, group_id, full_name, is_primary, category, attending, added_by_guest,
       gender, side, circle, ceremony_role, notes
from guests
order by is_primary desc, full_name
`

type ListAllGuestsRow struct {
	ID           uuid.UUID
	GroupID      uuid.UUID
	FullName     string
	IsPrimary    bool
	Category     *string
	Attending    string
	AddedByGuest bool
	Gender       *string
	Side         *string
	Circle       string
	CeremonyRole string
	Notes        string
}

func (q *Queries) ListAllGuests(ctx context.Context) ([]ListAllGuestsRow, error) {
	rows, err := q.db.Query(ctx, listAllGuests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllGuestsRow
	for rows.Next() {
		var i ListAllGuestsRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.FullName,
			&i.IsPrimary,
			&i.Category,
			&i.Attending,
			&i.AddedByGuest,
			&i.Gender,
			&i.Side,
			&i.Circle,
			&i.CeremonyRole,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupMembers = `-- name: ListGroupMembers :many
select id, full_name, is_primary, category, attending, added_by_guest,
       gender, side, circle, ceremony_role, notes
from guests
where group_id = $1
order by is_primary desc, full_name
`

type ListGroupMembersRow struct {
	ID           uuid.UUID
	FullName     string
	IsPrimary    bool
	Category     *string
	Attending    string
	AddedByGuest bool
	Gender       *string
	Side         *string
	Circle       string
	CeremonyRole string
	Notes        string
}

func (q *Queries) ListGroupMembers(ctx context.Context, groupID uuid.UUID) ([]ListGroupMembersRow, error) {
	rows, err := q.db.Query(ctx, listGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupMembersRow
	for rows.Next() {
		var i ListGroupMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.IsPrimary,
			&i.Category,
			&i.Attending,
			&i.AddedByGuest,
			&i.Gender,
			&i.Side,
			&i.Circle,
			&i.CeremonyRole,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteGroupIfEmpty = `-- name: DeleteGroupIfEmpty :exec
delete from guest_groups
where id = $1 and not exists (select 1 from guests where group_id = $1)
`

func (q *Queries) DeleteGroupIfEmpty(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteGroupIfEmpty, id)
	return err
}

const getGuestWithGroupSize = `-- name: GetGuestWithGroupSize :one
select g.id, g.group_id, g.full_name, g.is_primary, g.attending,
       (select count(*) from guests o where o.group_id = g.group_id) as group_size
from guests g
where g.id = $1
`

type GetGuestWithGroupSizeRow struct {
	ID        uuid.UUID
	GroupID   uuid.UUID
	FullName  string
	IsPrimary bool
	Attending string
	GroupSize int64
}

func (q *Queries) GetGuestWithGroupSize(ctx context.Context, id uuid.UUID) (GetGuestWithGroupSizeRow, error) {
	row := q.db.QueryRow(ctx, getGuestWithGroupSize, id)
	var i GetGuestWithGroupSizeRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.FullName,
		&i.IsPrimary,
		&i.Attending,
		&i.GroupSize,
	)
	return i, err
}

const insertGuestGroup = `-- name: InsertGuestGroup :one
insert into guest_groups (label)
values ($1)
returning id
`

func (q *Queries) InsertGuestGroup(ctx context.Context, label string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertGuestGroup, label)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const moveGuestToGroup = `-- name: MoveGuestToGroup :execrows
update guests
set group_id = $2, is_primary = false, added_by_guest = true, updated_at = now()
where id = $1
`

type MoveGuestToGroupParams struct {
	ID      uuid.UUID
	GroupID uuid.UUID
}

func (q *Queries) MoveGuestToGroup(ctx context.Context, arg MoveGuestToGroupParams) (int64, error) {
	result, err := q.db.Exec(ctx, moveGuestToGroup, arg.ID, arg.GroupID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const restoreCompanionToOwnGroup = `-- name: RestoreCompanionToOwnGroup :execrows
update guests
set group_id = $3, is_primary = true, added_by_guest = false, updated_at = now()
where id = $1 and group_id = $2 and added_by_guest
`

type RestoreCompanionToOwnGroupParams struct {
	ID         uuid.UUID
	GroupID    uuid.UUID
	NewGroupID uuid.UUID
}

func (q *Queries) RestoreCompanionToOwnGroup(ctx context.Context, arg RestoreCompanionToOwnGroupParams) (int64, error) {
	result, err := q.db.Exec(ctx, restoreCompanionToOwnGroup, arg.ID, arg.GroupID, arg.NewGroupID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const suggestAvailableCompanions = `-- name: SuggestAvailableCompanions :many
select g.id, g.full_name
from guests g
where g.normalized_name like $1::text || '%' escape '\'
  and g.group_id <> $2::uuid
  and (select count(*) from guests o where o.group_id = g.group_id) = 1
order by g.full_name
limit 8
`

type SuggestAvailableCompanionsParams struct {
	Prefix  string
	GroupID uuid.UUID
}

type SuggestAvailableCompanionsRow struct {
	ID       uuid.UUID
	FullName string
}

func (q *Queries) SuggestAvailableCompanions(ctx context.Context, arg SuggestAvailableCompanionsParams) ([]SuggestAvailableCompanionsRow, error) {
	rows, err := q.db.Query(ctx, suggestAvailableCompanions, arg.Prefix, arg.GroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SuggestAvailableCompanionsRow
	for rows.Next() {
		var i SuggestAvailableCompanionsRow
		if err := rows.Scan(&i.ID, &i.FullName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const suggestGuestNames = `-- name: SuggestGuestNames :many
select full_name
from guests
where normalized_name like $1::text || '%' escape '\'
order by full_name
limit 8
`

func (q *Queries) SuggestGuestNames(ctx context.Context, prefix string) ([]string, error) {
	rows, err := q.db.Query(ctx, suggestGuestNames, prefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var full_name string
		if err := rows.Scan(&full_name); err != nil {
			return nil, err
		}
		items = append(items, full_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countGroupCompanions = `-- name: CountGroupCompanions :one
select count(*)
from guests
where group_id = $1 and added_by_guest
`

func (q *Queries) CountGroupCompanions(ctx context.Context, groupID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countGroupCompanions, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const lockGroupForCompanion = `-- name: LockGroupForCompanion :one
select id
from guest_groups
where id = $1
for update
`

func (q *Queries) LockGroupForCompanion(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockGroupForCompanion, id)
	var id_ uuid.UUID
	err := row.Scan(&id_)
	return id_, err
}

const deleteGuest = `-- name: DeleteGuest :execrows
delete from guests where id = $1
`

func (q *Queries) DeleteGuest(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGuest, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const moveGuestToGroupAsAdmin = `-- name: MoveGuestToGroupAsAdmin :execrows
update guests
set group_id = $2, is_primary = false, updated_at = now()
where id = $1
`

type MoveGuestToGroupAsAdminParams struct {
	ID      uuid.UUID
	GroupID uuid.UUID
}

func (q *Queries) MoveGuestToGroupAsAdmin(ctx context.Context, arg MoveGuestToGroupAsAdminParams) (int64, error) {
	result, err := q.db.Exec(ctx, moveGuestToGroupAsAdmin, arg.ID, arg.GroupID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const renameGroup = `-- name: RenameGroup :execrows
update guest_groups set label = $2 where id = $1
`

type RenameGroupParams struct {
	ID    uuid.UUID
	Label string
}

func (q *Queries) RenameGroup(ctx context.Context, arg RenameGroupParams) (int64, error) {
	result, err := q.db.Exec(ctx, renameGroup, arg.ID, arg.Label)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setGroupPrimary = `-- name: SetGroupPrimary :execrows
update guests
set is_primary = (id = $1::uuid), updated_at = now()
where group_id = $2::uuid
`

type SetGroupPrimaryParams struct {
	GuestID uuid.UUID
	GroupID uuid.UUID
}

func (q *Queries) SetGroupPrimary(ctx context.Context, arg SetGroupPrimaryParams) (int64, error) {
	result, err := q.db.Exec(ctx, setGroupPrimary, arg.GuestID, arg.GroupID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateGuestDetails = `-- name: UpdateGuestDetails :execrows
update guests
set full_name = $2, normalized_name = $3, category = $4, gender = $5,
    side = $6, circle = $7, ceremony_role = $8, notes = $9, updated_at = now()
where id = $1
`

type UpdateGuestDetailsParams struct {
	ID             uuid.UUID
	FullName       string
	NormalizedName string
	Category       *string
	Gender         *string
	Side           *string
	Circle         string
	CeremonyRole   string
	Notes          string
}

func (q *Queries) UpdateGuestDetails(ctx context.Context, arg UpdateGuestDetailsParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateGuestDetails,
		arg.ID,
		arg.FullName,
		arg.NormalizedName,
		arg.Category,
		arg.Gender,
		arg.Side,
		arg.Circle,
		arg.CeremonyRole,
		arg.Notes,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateGuestAttendance = `-- name: UpdateGuestAttendance :execrows
update guests
set attending = $3, responded_at = now(), updated_at = now()
where id = $1 and group_id = $2
`

type UpdateGuestAttendanceParams struct {
	ID        uuid.UUID
	GroupID   uuid.UUID
	Attending string
}

func (q *Queries) UpdateGuestAttendance(ctx context.Context, arg UpdateGuestAttendanceParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateGuestAttendance, arg.ID, arg.GroupID, arg.Attending)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertGuest = `-- name: InsertGuest :one
insert into guests (group_id, full_name, normalized_name, is_primary, category,
                    gender, side, circle, ceremony_role, notes)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
returning id
`

type InsertGuestParams struct {
	GroupID        uuid.UUID
	FullName       string
	NormalizedName string
	IsPrimary      bool
	Category       *string
	Gender         *string
	Side           *string
	Circle         string
	CeremonyRole   string
	Notes          string
}

func (q *Queries) InsertGuest(ctx context.Context, arg InsertGuestParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertGuest,
		arg.GroupID,
		arg.FullName,
		arg.NormalizedName,
		arg.IsPrimary,
		arg.Category,
		arg.Gender,
		arg.Side,
		arg.Circle,
		arg.CeremonyRole,
		arg.Notes,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const ensureGroupHasPrimary = `-- name: EnsureGroupHasPrimary :exec
update guests
set is_primary = true, updated_at = now()
where id = (
  select id from guests
  where group_id = $1::uuid
  order by full_name
  limit 1
)
and not exists (
  select 1 from guests where group_id = $1::uuid and is_primary
)
`

func (q *Queries) EnsureGroupHasPrimary(ctx context.Context, groupID uuid.UUID) error {
	_, err := q.db.Exec(ctx, ensureGroupHasPrimary, groupID)
	return err
}
