// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: guests.sql

package guestsdb

import (
	"context"

	"github.com/google/uuid"
)

const getGuestByNormalizedName = `-- name: GetGuestByNormalizedName :one
select id, group_id, full_name, is_primary, category, attending
from guests
where normalized_name = $1
`

type GetGuestByNormalizedNameRow struct {
	ID        uuid.UUID
	GroupID   uuid.UUID
	FullName  string
	IsPrimary bool
	Category  *string
	Attending string
}

func (q *Queries) GetGuestByNormalizedName(ctx context.Context, normalizedName string) (GetGuestByNormalizedNameRow, error) {
	row := q.db.QueryRow(ctx, getGuestByNormalizedName, normalizedName)
	var i GetGuestByNormalizedNameRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.FullName,
		&i.IsPrimary,
		&i.Category,
		&i.Attending,
	)
	return i, err
}

const getGuestGroup = `-- name: GetGuestGroup :one
select id, label
from guest_groups
where id = $1
`

type GetGuestGroupRow struct {
	ID    uuid.UUID
	Label string
}

func (q *Queries) GetGuestGroup(ctx context.Context, id uuid.UUID) (GetGuestGroupRow, error) {
	row := q.db.QueryRow(ctx, getGuestGroup, id)
	var i GetGuestGroupRow
	err := row.Scan(&i.ID, &i.Label)
	return i, err
}

const listAllGroups = `-- name: ListAllGroups :many
select id, label
from guest_groups
order by label, id
`

type ListAllGroupsRow struct {
	ID    uuid.UUID
	Label string
}

func (q *Queries) ListAllGroups(ctx context.Context) ([]ListAllGroupsRow, error) {
	rows, err := q.db.Query(ctx, listAllGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllGroupsRow
	for rows.Next() {
		var i ListAllGroupsRow
		if err := rows.Scan(&i.ID, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllGuests = `-- name: ListAllGuests :many
select id, group_id, full_name, is_primary, category, attending
from guests
order by is_primary desc, full_name
`

type ListAllGuestsRow struct {
	ID        uuid.UUID
	GroupID   uuid.UUID
	FullName  string
	IsPrimary bool
	Category  *string
	Attending string
}

func (q *Queries) ListAllGuests(ctx context.Context) ([]ListAllGuestsRow, error) {
	rows, err := q.db.Query(ctx, listAllGuests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllGuestsRow
	for rows.Next() {
		var i ListAllGuestsRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.FullName,
			&i.IsPrimary,
			&i.Category,
			&i.Attending,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupMembers = `-- name: ListGroupMembers :many
select id, full_name, is_primary, category, attending, added_by_guest
from guests
where group_id = $1
order by is_primary desc, full_name
`

type ListGroupMembersRow struct {
	ID           uuid.UUID
	FullName     string
	IsPrimary    bool
	Category     *string
	Attending    string
	AddedByGuest bool
}

func (q *Queries) ListGroupMembers(ctx context.Context, groupID uuid.UUID) ([]ListGroupMembersRow, error) {
	rows, err := q.db.Query(ctx, listGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupMembersRow
	for rows.Next() {
		var i ListGroupMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.IsPrimary,
			&i.Category,
			&i.Attending,
			&i.AddedByGuest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const suggestGuestNames = `-- name: SuggestGuestNames :many
select full_name
from guests
where normalized_name like $1::text || '%' escape '\'
order by full_name
limit 8
`

func (q *Queries) SuggestGuestNames(ctx context.Context, prefix string) ([]string, error) {
	rows, err := q.db.Query(ctx, suggestGuestNames, prefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var full_name string
		if err := rows.Scan(&full_name); err != nil {
			return nil, err
		}
		items = append(items, full_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countGroupCompanions = `-- name: CountGroupCompanions :one
select count(*)
from guests
where group_id = $1 and added_by_guest
`

func (q *Queries) CountGroupCompanions(ctx context.Context, groupID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countGroupCompanions, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertCompanion = `-- name: InsertCompanion :one
insert into guests (group_id, full_name, normalized_name, category, attending,
                    responded_at, added_by_guest)
values ($1, $2, $3, 'adult', $4, now(), true)
returning id, full_name, is_primary, category, attending
`

type InsertCompanionParams struct {
	GroupID        uuid.UUID
	FullName       string
	NormalizedName string
	Attending      string
}

type InsertCompanionRow struct {
	ID        uuid.UUID
	FullName  string
	IsPrimary bool
	Category  *string
	Attending string
}

func (q *Queries) InsertCompanion(ctx context.Context, arg InsertCompanionParams) (InsertCompanionRow, error) {
	row := q.db.QueryRow(ctx, insertCompanion,
		arg.GroupID,
		arg.FullName,
		arg.NormalizedName,
		arg.Attending,
	)
	var i InsertCompanionRow
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.IsPrimary,
		&i.Category,
		&i.Attending,
	)
	return i, err
}

const lockGroupForCompanion = `-- name: LockGroupForCompanion :one
select id
from guest_groups
where id = $1
for update
`

func (q *Queries) LockGroupForCompanion(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockGroupForCompanion, id)
	var id_ uuid.UUID
	err := row.Scan(&id_)
	return id_, err
}

const updateGuestAttendance = `-- name: UpdateGuestAttendance :execrows
update guests
set attending = $3, responded_at = now(), updated_at = now()
where id = $1 and group_id = $2
`

type UpdateGuestAttendanceParams struct {
	ID        uuid.UUID
	GroupID   uuid.UUID
	Attending string
}

func (q *Queries) UpdateGuestAttendance(ctx context.Context, arg UpdateGuestAttendanceParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateGuestAttendance, arg.ID, arg.GroupID, arg.Attending)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
