// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: content.sql

package contentdb

import (
	"context"
)

const getSection = `-- name: GetSection :one
select slug, payload, enabled, updated_at
from sections
where slug = $1
`

func (q *Queries) GetSection(ctx context.Context, slug string) (Section, error) {
	row := q.db.QueryRow(ctx, getSection, slug)
	var i Section
	err := row.Scan(
		&i.Slug,
		&i.Payload,
		&i.Enabled,
		&i.UpdatedAt,
	)
	return i, err
}

const listSections = `-- name: ListSections :many
select slug, payload, enabled, updated_at
from sections
order by slug
`

func (q *Queries) ListSections(ctx context.Context) ([]Section, error) {
	rows, err := q.db.Query(ctx, listSections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Section
	for rows.Next() {
		var i Section
		if err := rows.Scan(
			&i.Slug,
			&i.Payload,
			&i.Enabled,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSection = `-- name: UpdateSection :one
update sections
set payload = $2, enabled = $3, updated_at = now()
where slug = $1
returning slug, payload, enabled, updated_at
`

type UpdateSectionParams struct {
	Slug    string
	Payload []byte
	Enabled bool
}

func (q *Queries) UpdateSection(ctx context.Context, arg UpdateSectionParams) (Section, error) {
	row := q.db.QueryRow(ctx, updateSection, arg.Slug, arg.Payload, arg.Enabled)
	var i Section
	err := row.Scan(
		&i.Slug,
		&i.Payload,
		&i.Enabled,
		&i.UpdatedAt,
	)
	return i, err
}
