// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: media.sql

package mediadb

import (
	"context"

	"github.com/google/uuid"
)

const deleteMedia = `-- name: DeleteMedia :execrows
delete from media
where id = $1
`

func (q *Queries) DeleteMedia(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMedia, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMedia = `-- name: GetMedia :one
select id, bucket_path, public_url, alt, created_at
from media
where id = $1
`

func (q *Queries) GetMedia(ctx context.Context, id uuid.UUID) (Medium, error) {
	row := q.db.QueryRow(ctx, getMedia, id)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.BucketPath,
		&i.PublicUrl,
		&i.Alt,
		&i.CreatedAt,
	)
	return i, err
}

const insertMedia = `-- name: InsertMedia :one
insert into media (bucket_path, public_url, alt)
values ($1, $2, $3)
returning id, bucket_path, public_url, alt, created_at
`

type InsertMediaParams struct {
	BucketPath string
	PublicUrl  string
	Alt        *string
}

func (q *Queries) InsertMedia(ctx context.Context, arg InsertMediaParams) (Medium, error) {
	row := q.db.QueryRow(ctx, insertMedia, arg.BucketPath, arg.PublicUrl, arg.Alt)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.BucketPath,
		&i.PublicUrl,
		&i.Alt,
		&i.CreatedAt,
	)
	return i, err
}

const listMedia = `-- name: ListMedia :many
select id, bucket_path, public_url, alt, created_at
from media
order by created_at desc
`

func (q *Queries) ListMedia(ctx context.Context) ([]Medium, error) {
	rows, err := q.db.Query(ctx, listMedia)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Medium
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.BucketPath,
			&i.PublicUrl,
			&i.Alt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
