// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: messages.sql

package messagesdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertMessage = `-- name: InsertMessage :one
insert into messages (group_id, author_name, body)
values ($1, $2, $3)
returning id, group_id, author_name, body, created_at
`

type InsertMessageParams struct {
	GroupID    uuid.NullUUID
	AuthorName string
	Body       string
}

type InsertMessageRow struct {
	ID         uuid.UUID
	GroupID    uuid.NullUUID
	AuthorName string
	Body       string
	CreatedAt  time.Time
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (InsertMessageRow, error) {
	row := q.db.QueryRow(ctx, insertMessage, arg.GroupID, arg.AuthorName, arg.Body)
	var i InsertMessageRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.AuthorName,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const listMessages = `-- name: ListMessages :many
select id, group_id, author_name, body, created_at
from messages
order by created_at desc
`

type ListMessagesRow struct {
	ID         uuid.UUID
	GroupID    uuid.NullUUID
	AuthorName string
	Body       string
	CreatedAt  time.Time
}

func (q *Queries) ListMessages(ctx context.Context) ([]ListMessagesRow, error) {
	rows, err := q.db.Query(ctx, listMessages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessagesRow{}
	for rows.Next() {
		var i ListMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.AuthorName,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
