// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: messages.sql

package messagesdb

import (
	"context"

	"github.com/google/uuid"
)

const insertMessage = `-- name: InsertMessage :one
insert into messages (group_id, author_name, body)
values ($1, $2, $3)
returning id, group_id, author_name, body, status, created_at
`

type InsertMessageParams struct {
	GroupID    uuid.NullUUID
	AuthorName string
	Body       string
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, insertMessage, arg.GroupID, arg.AuthorName, arg.Body)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.AuthorName,
		&i.Body,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listMessages = `-- name: ListMessages :many
select id, group_id, author_name, body, status, created_at
from messages
where ($1::text = '' or status = $1::text)
order by created_at desc
`

func (q *Queries) ListMessages(ctx context.Context, statusFilter string) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessages, statusFilter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.AuthorName,
			&i.Body,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMessageStatus = `-- name: UpdateMessageStatus :one
update messages
set status = $2
where id = $1
returning id, group_id, author_name, body, status, created_at
`

type UpdateMessageStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdateMessageStatus(ctx context.Context, arg UpdateMessageStatusParams) (Message, error) {
	row := q.db.QueryRow(ctx, updateMessageStatus, arg.ID, arg.Status)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.AuthorName,
		&i.Body,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
